export const REQUEST_REPORT_DATA = 'REQUEST_REPORT_DATA';
export const REQUEST_DASHBOARD_BATCHES = 'REQUEST_DASHBOARD_BATCHES';
export const RECEIVE_DASHBOARD_BATCHES = 'RECEIVE_DASHBOARD_BATCHES';
export const UPDATE_DASHBOARD_FILTER = 'UPDATE_DASHBOARD_FILTER';
export const RECEIVE_TOPIC_REPORT = 'RECEIVE_TOPIC_REPORT';
export const RECEIVE_EXERCISE_REPORT = 'RECEIVE_EXERCISE_REPORT';
