export const REQUEST_EXERCISES = 'REQUEST_EXERCISES';
export const RECEIVE_EXERCISES = 'RECEIVE_EXERCISES';
export const REQUEST_EXERCISES_UPDATE = 'REQUEST_EXERCISES_UPDATE';
export const RECEIVE_EXERCISES_ERROR = 'RECEIVE_EXERCISES_ERROR';
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const REQUEST_EXERCISE_EDIT = 'REQUEST_EXERCISE_EDIT';
export const RECEIVE_EXERCISE_EDIT = 'RECEIVE_EXERCISE_EDIT';
export const RECEIVE_EXERCISE_DELETE = 'RECEIVE_EXERCISE_DELETE';
export const RECEIVE_TOPICS = 'RECEIVE_TOPICS';

export const EXERCISE_NAME_MISSING = 'Please enter exercise name';
export const EXERCISE_TOPIC_MISSING = 'Please select topic';
export const EXERCISE_DAY_INVALID = 'Day is invalid';
