export const REQUEST_TOPICS = 'REQUEST_TOPICS';
export const RECEIVE_TOPICS = 'RECEIVE_TOPICS';
export const REQUEST_TOPICS_UPDATE = 'REQUEST_TOPICS_UPDATE';
export const RECEIVE_TOPICS_UPDATE = 'RECEIVE_TOPICS_UPDATE';
export const ADD_TOPIC = 'ADD_TOPIC';
export const UPDATE_TOPIC = 'UPDATE_TOPIC';
export const DELETE_TOPIC = 'DELETE_TOPIC';
