language: node_js
node_js:
- '9'
jobs:
  include:
    -stage: Tests
    script: yarn test
    -stage: Deploy API
    script: cd packages/api && yarn build
    deploy: &heroku
      provider: heroku
      api_key:
        secure: MPFBXdZ7jtWuPn6sJHHwMSh7cJBjqxzRJ4PB8TzQV6CAnf0Nk7XpYv56BfWbJYmiSaJw76XK7vZYVNYUsombhu1xQYhCl8W7VKFrctiRZxU+qlUCRBq5KixY3FYaoV62L5Z8RnDAl5K7tga/DBPWndmY8XkMkblmBfEeJs9jx3ORFBh4bOrWlzfTLbDNKRDyKN8hrJTzWWWfGDSb/HxzVQL4dTVFwbvJ2rdCGBiaLLTfcp8oyxf4CSaGZll66ja9vJYhPvhnXYbuMrUBgRBaKsAxKUPYG71u+qoCsYpGaXhXhutI0dlw6aNIZk+gesaOfiXRM3Vk7ydXeVJ3Ps7ngn0R7KkKKXoI1ZNIEU1A6OosdntQ4HtLsRrcp4dy7+A7zxqcuhRfDfrFtF67Gfjek3ugP4tXwO60hf3jsqzz5fCH3CCSXpMdbNDiuQlx9xu5jdmfTl7iuk7oMEh1U0ACjSSt5djnt7mFr0ixziO/+AQkpRxFXrwYm08erPgeAybbpaDH86WeuaWQqdCT18Q0EyRGN+5kQGx3kmW45gSDWD5YIzTaMKpwdinqWsbzMu31rIYqhjzxugEuhwcxLDbaq/9Nsz9yRWUzuruWde5gYs1wLQSO8w0ud/xWwdM9/xpAZHd1e0l73RJJQXETb1JVq6ptLV6Hwyv/JzEMbJWwOLI=
      skip_cleanup: true
      app:
        master: deltapesto-api
    -stage: Deploy Students
    script: cd packages/students && yarn build
    deploy:
      <<: *heroku
      app:
        master: deltapesto
    -stage: Deploy Instructors
    script: cd packages/instructors && yarn build
    deploy:
      <<: *heroku
      app:
        master: deltapesto-instructors
