module.exports = {
  missingOriginHeader: 'REQUEST_MISSING_ORIGIN_HEADER',
  invalidToken: 'TOKEN_INVALID',
  missingToken: 'TOKEN_MISSING',
  expiredToken: 'TOKEN_EXPIRED',
  missingEmail: 'EMAIL_MISSING',
  invalidEmail: 'EMAIL_INVALID',
  noEmail: 'NO_EMAIL_PROVIDED',
  noFirstName: 'NO_FIRSTNAME_PROVIDED',
  noLastName: 'NO_LASTNAME_PROVIDED',
  noProfilePicture: 'NO_PROFILE_PICTURE',
  noRole: 'NO_ROLE_PROVIDED',
  noBatchId: 'NO_BATCH_ID_OR_INSUFFCIENT_LENGTH',
  noProfileData: 'NO_PROFILE_DATA_PROVIDED',
  internalServerError: 'Server error',
  noPort: 'Express: Port number is not specified',
  noDBUrl: 'Database: Database url is not specified',
  missingInfo: 'Some information is missing',
};
